### ISSUE TITLE
Unable to compile ed25519 for a web project

### ISSUE THREAD

**Issue by sygem** [Tougee/ed25519#1]
I'm trying to use ed25519 in a web project - unfortunately it won't compile to Javascript.

These are the errors I am getting:

```
../../flutter/.pub-cache/hosted/pub.dartlang.org/ed25519_edwards-0.1.0/lib/src/edwards25519.dart:2099:6: Error: The integer literal 0x5812631a5cf5d3ed can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x5812631a5cf5d400 is the nearest value that can be represented exactly.
    [0x5812631a5cf5d3ed, 0x14def9dea2f79cd6, 0, 0x1000000000000000]);
     ^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/ed25519_edwards-0.1.0/lib/src/edwards25519.dart:2099:26: Error: The integer literal 0x14def9dea2f79cd6 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x14def9dea2f79d00 is the nearest value that can be represented exactly.
    [0x5812631a5cf5d3ed, 0x14def9dea2f79cd6, 0, 0x1000000000000000]);
                         ^^^^^^^^^^^^^^^^^^
```

My `flutter doctor` output:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.928], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)

• No issues found!
```

**Comment by Tougee** [comment]
Thanks for reporting this, something that may not work when compiled to JS.
https://github.com/flutter/flutter/issues/61500

Maybe I should rewrite some parts with `BigInt`, but it can take unpredictable amounts of time and I'm not sure when this will be completed.

**Comment by crossle** [comment]
Welcome contribute.

**Comment by kingsleyh** [comment]
Hi - I'm interested in the same fix.

**Comment by kingsleyh** [comment]
I did a quick hack to make it work - by restricting the values in the order for the curve to the max values that Javascript can handle which is by editing line 2099 in edwards25519.dart to the following:

```dart
/// order is the order of Curve25519 in little-endian form.
var order = List<int>.from(
    [0x5812631a5cf5d400, 0x14def9dea2f79d00, 0, 0x1000000000000000]);
```

All the tests still pass and it starts up and runs correctly in Chrome as well. But I don't know if this is acceptable solution.

**Comment by Tougee** [comment]
I am trying to rewrite some calculation methods using BigInt in https://github.com/Tougee/ed25519/commit/dc2a6a904c90723ce28d47ecc8c59f24e44756f1
All tests passed, but the tests execution takes a long time, so I will not using that change in releases until find a better way to resolve this.

@sygem if you still want to use this library, I think you can try @kingsleyh 's workaround for JS specific platforms, I'm not checking that worked and will not be using that solution in the release either.

**Comment by kingsleyh** [comment]
Often BigInt or BigDecimal are much slower but not sure if that’s the case in Dart.

JavaScript only seems to complain about the size of the order curve so maybe that’s all that needs converting to BigInt but not really sure

**Comment by Tougee** [comment]
Fixed in https://github.com/Tougee/ed25519/pull/2
