### ISSUE TITLE
Private Key Size

### ISSUE THREAD

**Issue by redDwarf03** [Tougee/ed25519#3]
Hello
thank for your library
I have a question. You specify the length of the private key with the value : 64
but in the RFC8032 documentation, they precise "_The private key is 32 octets_"
ref = [https://datatracker.ietf.org/doc/html/rfc8032#section-5.1.5](https://datatracker.ietf.org/doc/html/rfc8032#section-5.1.5)

Could you help me please

**Comment by Tougee** [comment]
This library is a port of Go Ed25519, and in this implementation, `privateKey = seed||publicKey`, the seed correspond to private key in rfc8032.

**Comment by redDwarf03** [comment]
thx
